name: rheel_estate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.30+28

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.5
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  mailer: ^6.4.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  connectivity_plus: ^6.1.2
  intl: ^0.20.2
  dio: ^5.7.0
  http_parser: ^4.0.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  flutter_facebook_auth: ^7.1.1
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  loading_animation_widget: ^1.3.0
  flutter_local_notifications: ^18.0.1
  photo_view: ^0.15.0
  internet_connection_checker: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^5.0.0




# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.otf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.otf
          style: italic
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.otf
          weight: 600
          style: italic